mysql:
  image: mysql:5.7.22
  privileged: false
  restart: always
  ports:
  - 3308:3306
  volumes:
  - /Volumes/data/docker/mysql/data:/var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=root
sync-engine:
  image: 'gnuhub/sync-engine:latest'
  restart: always
  ports:
    - '9999:9999'
  links:
    - mysql
