mysql:
  image: mysql:5.7.22
  privileged: false
  restart: always
  ports:
  - 3308:3306
  environment:
  - MYSQL_ROOT_PASSWORD=root
redis:
  image: redis:latest
  privileged: false
  restart: always
  ports:
  - 6380:6379
sync-engine:
  image: index.docker.io/gnuhub/sync-engine:latest
  privileged: false
  restart: always
  links:
  - mysql
  - redis
  command: bash /home/syncengine4/docker.start.engine.sh
sync-engine-api:
  image: index.docker.io/gnuhub/sync-engine:latest
  privileged: false
  restart: always
  ports:
  - 9999:9999
  links:
  - mysql
  - redis
  command: bash /home/syncengine4/docker.start.api.sh
